name: Docker Image CI

on:
  push:
    branches: [ rebased ]
  pull_request:
    branches: [ rebased ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image and test
      run: docker build . --file .github/workflows/Dockerfile --tag ubuntu-bolt:$(date +%s)
